; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; FIXME: @llvm.canonicalize doesn't support soft-float abi yet.
; RUN: llc -mtriple=riscv64 -mattr=+d,+zfh -global-isel -target-abi=lp64d < %s | FileCheck %s --check-prefixes=CHECK,CHECK-FP16-RV64
; RUN: llc -mtriple=riscv64 -mattr=+d,-zfh -global-isel -target-abi=lp64d < %s | FileCheck %s --check-prefixes=CHECK,CHECK-NOFP16-RV64
; RUN: llc -mtriple=riscv32 -mattr=+d,+zfh -global-isel -target-abi=ilp32d < %s | FileCheck %s --check-prefixes=CHECK,CHECK-FP16-RV32
; RUN: llc -mtriple=riscv32 -mattr=+d,-zfh -global-isel -target-abi=ilp32d < %s | FileCheck %s --check-prefixes=CHECK,CHECK-NOFP16-RV32

declare half @llvm.fcanonicalize.f16(half)
declare float @llvm.fcanonicalize.f32(float)
declare double @llvm.fcanonicalize.f64(double)

define half @fcanonicalize_f16(half %x) {
; CHECK-FP16-RV64-LABEL: fcanonicalize_f16:
; CHECK-FP16-RV64:       # %bb.0:
; CHECK-FP16-RV64-NEXT:    fmin.h fa0, fa0, fa0
; CHECK-FP16-RV64-NEXT:    ret
;
; CHECK-NOFP16-RV64-LABEL: fcanonicalize_f16:
; CHECK-NOFP16-RV64:       # %bb.0:
; CHECK-NOFP16-RV64-NEXT:    addi sp, sp, -16
; CHECK-NOFP16-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NOFP16-RV64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NOFP16-RV64-NEXT:    .cfi_offset ra, -8
; CHECK-NOFP16-RV64-NEXT:    call __extendhfsf2
; CHECK-NOFP16-RV64-NEXT:    fmin.s fa0, fa0, fa0
; CHECK-NOFP16-RV64-NEXT:    call __truncsfhf2
; CHECK-NOFP16-RV64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NOFP16-RV64-NEXT:    .cfi_restore ra
; CHECK-NOFP16-RV64-NEXT:    addi sp, sp, 16
; CHECK-NOFP16-RV64-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NOFP16-RV64-NEXT:    ret
;
; CHECK-FP16-RV32-LABEL: fcanonicalize_f16:
; CHECK-FP16-RV32:       # %bb.0:
; CHECK-FP16-RV32-NEXT:    fmin.h fa0, fa0, fa0
; CHECK-FP16-RV32-NEXT:    ret
;
; CHECK-NOFP16-RV32-LABEL: fcanonicalize_f16:
; CHECK-NOFP16-RV32:       # %bb.0:
; CHECK-NOFP16-RV32-NEXT:    addi sp, sp, -16
; CHECK-NOFP16-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NOFP16-RV32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; CHECK-NOFP16-RV32-NEXT:    .cfi_offset ra, -4
; CHECK-NOFP16-RV32-NEXT:    call __extendhfsf2
; CHECK-NOFP16-RV32-NEXT:    fmin.s fa0, fa0, fa0
; CHECK-NOFP16-RV32-NEXT:    call __truncsfhf2
; CHECK-NOFP16-RV32-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; CHECK-NOFP16-RV32-NEXT:    .cfi_restore ra
; CHECK-NOFP16-RV32-NEXT:    addi sp, sp, 16
; CHECK-NOFP16-RV32-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NOFP16-RV32-NEXT:    ret
  %z = call half @llvm.canonicalize.f16(half %x)
  ret half %z
}

define half @fcanonicalize_f16_nnan(half %x) {
; CHECK-FP16-RV64-LABEL: fcanonicalize_f16_nnan:
; CHECK-FP16-RV64:       # %bb.0:
; CHECK-FP16-RV64-NEXT:    fmin.h fa0, fa0, fa0
; CHECK-FP16-RV64-NEXT:    ret
;
; CHECK-NOFP16-RV64-LABEL: fcanonicalize_f16_nnan:
; CHECK-NOFP16-RV64:       # %bb.0:
; CHECK-NOFP16-RV64-NEXT:    addi sp, sp, -16
; CHECK-NOFP16-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NOFP16-RV64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NOFP16-RV64-NEXT:    .cfi_offset ra, -8
; CHECK-NOFP16-RV64-NEXT:    call __extendhfsf2
; CHECK-NOFP16-RV64-NEXT:    fmin.s fa0, fa0, fa0
; CHECK-NOFP16-RV64-NEXT:    call __truncsfhf2
; CHECK-NOFP16-RV64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NOFP16-RV64-NEXT:    .cfi_restore ra
; CHECK-NOFP16-RV64-NEXT:    addi sp, sp, 16
; CHECK-NOFP16-RV64-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NOFP16-RV64-NEXT:    ret
;
; CHECK-FP16-RV32-LABEL: fcanonicalize_f16_nnan:
; CHECK-FP16-RV32:       # %bb.0:
; CHECK-FP16-RV32-NEXT:    fmin.h fa0, fa0, fa0
; CHECK-FP16-RV32-NEXT:    ret
;
; CHECK-NOFP16-RV32-LABEL: fcanonicalize_f16_nnan:
; CHECK-NOFP16-RV32:       # %bb.0:
; CHECK-NOFP16-RV32-NEXT:    addi sp, sp, -16
; CHECK-NOFP16-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NOFP16-RV32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; CHECK-NOFP16-RV32-NEXT:    .cfi_offset ra, -4
; CHECK-NOFP16-RV32-NEXT:    call __extendhfsf2
; CHECK-NOFP16-RV32-NEXT:    fmin.s fa0, fa0, fa0
; CHECK-NOFP16-RV32-NEXT:    call __truncsfhf2
; CHECK-NOFP16-RV32-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; CHECK-NOFP16-RV32-NEXT:    .cfi_restore ra
; CHECK-NOFP16-RV32-NEXT:    addi sp, sp, 16
; CHECK-NOFP16-RV32-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NOFP16-RV32-NEXT:    ret
  %z = call nnan half @llvm.canonicalize.f16(half %x)
  ret half %z
}

define float @fcanonicalize_f32(float %x) {
; CHECK-LABEL: fcanonicalize_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmin.s fa0, fa0, fa0
; CHECK-NEXT:    ret
  %z = call float @llvm.canonicalize.f32(float %x)
  ret float %z
}

define float @fcanonicalize_f32_nnan(float %x) {
; CHECK-LABEL: fcanonicalize_f32_nnan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmin.s fa0, fa0, fa0
; CHECK-NEXT:    ret
  %z = call nnan float @llvm.canonicalize.f32(float %x)
  ret float %z
}

define double @fcanonicalize_f64(double %x) {
; CHECK-LABEL: fcanonicalize_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmin.d fa0, fa0, fa0
; CHECK-NEXT:    ret
  %z = call double @llvm.canonicalize.f64(double %x)
  ret double %z
}

define double @fcanonicalize_f64_nnan(double %x) {
; CHECK-LABEL: fcanonicalize_f64_nnan:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmin.d fa0, fa0, fa0
; CHECK-NEXT:    ret
  %z = call nnan double @llvm.canonicalize.f64(double %x)
  ret double %z
}

; strip vector lowering part
