; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=zfbfmin -verify-machineinstrs < %s \
; RUN:   -target-abi=ilp32f | FileCheck -check-prefix=RV32ZFH %s
; RUN: llc -mtriple=riscv64 -mattr=zfbfmin -verify-machineinstrs < %s \
; RUN:   -target-abi=lp64f | FileCheck -check-prefix=RV64ZFH %s
; RUN: llc -mtriple=riscv32 -mattr=zfbfmin,+d -verify-machineinstrs < %s \
; RUN:   -target-abi=ilp32d | FileCheck -check-prefix=RV32DZFH %s
; RUN: llc -mtriple=riscv64 -mattr=zfbfmin,+d -verify-machineinstrs < %s \
; RUN:   -target-abi=lp64d | FileCheck -check-prefix=RV64DZFH %s

@gh = external global bfloat

define bfloat @constraint_f_bfloat() nounwind {
; RV32ZFH-LABEL: constraint_f_bfloat:
; RV32ZFH:       # %bb.0:
; RV32ZFH-NEXT:    lui a0, %hi(gh)
; RV32ZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    ret
;
; RV64ZFH-LABEL: constraint_f_bfloat:
; RV64ZFH:       # %bb.0:
; RV64ZFH-NEXT:    lui a0, %hi(gh)
; RV64ZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    ret
;
; RV32DZFH-LABEL: constraint_f_bfloat:
; RV32DZFH:       # %bb.0:
; RV32DZFH-NEXT:    lui a0, %hi(gh)
; RV32DZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    ret
;
; RV64DZFH-LABEL: constraint_f_bfloat:
; RV64DZFH:       # %bb.0:
; RV64DZFH-NEXT:    lui a0, %hi(gh)
; RV64DZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    ret
  %1 = load bfloat, ptr @gh
  %2 = tail call float asm "fcvt.s.bf16 $0, $1", "=f,f"(bfloat %1)
  %3 = tail call bfloat asm "fcvt.bf16.s $0, $1", "=f,f"(float %2)
  ret bfloat %3
}

define bfloat @constraint_cf_bfloat() nounwind {
; RV32ZFH-LABEL: constraint_cf_bfloat:
; RV32ZFH:       # %bb.0:
; RV32ZFH-NEXT:    lui a0, %hi(gh)
; RV32ZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    ret
;
; RV64ZFH-LABEL: constraint_cf_bfloat:
; RV64ZFH:       # %bb.0:
; RV64ZFH-NEXT:    lui a0, %hi(gh)
; RV64ZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    ret
;
; RV32DZFH-LABEL: constraint_cf_bfloat:
; RV32DZFH:       # %bb.0:
; RV32DZFH-NEXT:    lui a0, %hi(gh)
; RV32DZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    ret
;
; RV64DZFH-LABEL: constraint_cf_bfloat:
; RV64DZFH:       # %bb.0:
; RV64DZFH-NEXT:    lui a0, %hi(gh)
; RV64DZFH-NEXT:    flh fa5, %lo(gh)(a0)
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    fcvt.s.bf16 fa5, fa5
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    fcvt.bf16.s fa0, fa5
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    ret
  %1 = load bfloat, ptr @gh
  %2 = tail call float asm "fcvt.s.bf16 $0, $1", "=^cf,^cf"(bfloat %1)
  %3 = tail call bfloat asm "fcvt.bf16.s $0, $1", "=^cf,^cf"(float %2)
  ret bfloat %3
}

define bfloat @constraint_f_bfloat_abi_name() nounwind {
; RV32ZFH-LABEL: constraint_f_bfloat_abi_name:
; RV32ZFH:       # %bb.0:
; RV32ZFH-NEXT:    lui a0, %hi(gh)
; RV32ZFH-NEXT:    flh fa0, %lo(gh)(a0)
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    fcvt.s.bf16 ft0, fa0
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    fmv.s fa0, ft0
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    fcvt.bf16.s ft0, fa0
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    fmv.s fa0, ft0
; RV32ZFH-NEXT:    ret
;
; RV64ZFH-LABEL: constraint_f_bfloat_abi_name:
; RV64ZFH:       # %bb.0:
; RV64ZFH-NEXT:    lui a0, %hi(gh)
; RV64ZFH-NEXT:    flh fa0, %lo(gh)(a0)
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    fcvt.s.bf16 ft0, fa0
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    fmv.s fa0, ft0
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    fcvt.bf16.s ft0, fa0
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    fmv.s fa0, ft0
; RV64ZFH-NEXT:    ret
;
; RV32DZFH-LABEL: constraint_f_bfloat_abi_name:
; RV32DZFH:       # %bb.0:
; RV32DZFH-NEXT:    lui a0, %hi(gh)
; RV32DZFH-NEXT:    flh fa0, %lo(gh)(a0)
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    fcvt.s.bf16 ft0, fa0
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    fmv.s fa0, ft0
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    fcvt.bf16.s ft0, fa0
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    fmv.s fa0, ft0
; RV32DZFH-NEXT:    ret
;
; RV64DZFH-LABEL: constraint_f_bfloat_abi_name:
; RV64DZFH:       # %bb.0:
; RV64DZFH-NEXT:    lui a0, %hi(gh)
; RV64DZFH-NEXT:    flh fa0, %lo(gh)(a0)
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    fcvt.s.bf16 ft0, fa0
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    fmv.s fa0, ft0
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    fcvt.bf16.s ft0, fa0
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    fmv.s fa0, ft0
; RV64DZFH-NEXT:    ret
  %1 = load bfloat, ptr @gh
  %2 = tail call float asm "fcvt.s.bf16 $0, $1", "={ft0},{fa0}"(bfloat %1)
  %3 = tail call bfloat asm "fcvt.bf16.s $0, $1", "={ft0},{fa0}"(float %2)
  ret bfloat %3
}

define bfloat @constraint_gpr(bfloat %x) {
; RV32ZFH-LABEL: constraint_gpr:
; RV32ZFH:       # %bb.0:
; RV32ZFH-NEXT:    fmv.x.h a0, fa0
; RV32ZFH-NEXT:    #APP
; RV32ZFH-NEXT:    mv a0, a0
; RV32ZFH-NEXT:    #NO_APP
; RV32ZFH-NEXT:    fmv.h.x fa0, a0
; RV32ZFH-NEXT:    ret
;
; RV64ZFH-LABEL: constraint_gpr:
; RV64ZFH:       # %bb.0:
; RV64ZFH-NEXT:    fmv.x.h a0, fa0
; RV64ZFH-NEXT:    #APP
; RV64ZFH-NEXT:    mv a0, a0
; RV64ZFH-NEXT:    #NO_APP
; RV64ZFH-NEXT:    fmv.h.x fa0, a0
; RV64ZFH-NEXT:    ret
;
; RV32DZFH-LABEL: constraint_gpr:
; RV32DZFH:       # %bb.0:
; RV32DZFH-NEXT:    fmv.x.h a0, fa0
; RV32DZFH-NEXT:    #APP
; RV32DZFH-NEXT:    mv a0, a0
; RV32DZFH-NEXT:    #NO_APP
; RV32DZFH-NEXT:    fmv.h.x fa0, a0
; RV32DZFH-NEXT:    ret
;
; RV64DZFH-LABEL: constraint_gpr:
; RV64DZFH:       # %bb.0:
; RV64DZFH-NEXT:    fmv.x.h a0, fa0
; RV64DZFH-NEXT:    #APP
; RV64DZFH-NEXT:    mv a0, a0
; RV64DZFH-NEXT:    #NO_APP
; RV64DZFH-NEXT:    fmv.h.x fa0, a0
; RV64DZFH-NEXT:    ret
  %1 = tail call bfloat asm sideeffect alignstack "mv $0, $1", "={x10},{x10}"(bfloat %x)
  ret bfloat %1
}
